services:
  - type: web
    name: commentboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: commentboard.settings
      - key: SECRET_KEY
        generateValue: true